export const ENROLLME_ADMIN_ROLES = ["super_admin", "compliance_manager", "reviewer"];

export const DRIVER_ONBOARDING_STATUSES = [
  "invited",
  "in_progress",
  "driver_submitted",
  "admin_review_pending",
  "correction_requested",
  "admin_items_pending",
  "government_ready",
  "approved_to_operate",
  "rejected",
  "archived",
  // Legacy statuses are accepted so existing records can still be opened and migrated by normal saves.
  "draft",
  "submitted",
  "approved",
];

export const ENROLLME_DOCUMENT_TYPES = {
  DRIVER_APPLICATION: "driver_application",
  WC43_REJECTION: "wc43_rejection",
  INDEPENDENT_CONTRACTOR_AGREEMENT: "independent_contractor_agreement",
  AGREEMENT_QUIZ: "agreement_quiz",
  TRAINING_ACKNOWLEDGMENT: "training_acknowledgment",
  VIOLATION_CERTIFICATION: "violation_certification_annual_review",
  VEHICLE_INSPECTION: "vehicle_inspection_report",
  PREVENTIVE_MAINTENANCE: "preventive_maintenance_plan",
};

export const ENROLLME_STEPS = [
  {
    key: "identity",
    title: "Identity and Address",
    documentType: ENROLLME_DOCUMENT_TYPES.DRIVER_APPLICATION,
    stage: "Intake",
  },
  {
    key: "employment-application",
    title: "License and Driving Experience",
    documentType: ENROLLME_DOCUMENT_TYPES.DRIVER_APPLICATION,
    stage: "Intake",
  },
  {
    key: "safety-performance",
    title: "Safety Performance / Previous Employer Authorization",
    documentType: ENROLLME_DOCUMENT_TYPES.DRIVER_APPLICATION,
    stage: "Intake",
  },
  {
    key: "accident-violation-history",
    title: "Accident and Violation History",
    documentType: ENROLLME_DOCUMENT_TYPES.VIOLATION_CERTIFICATION,
    stage: "Intake",
  },
  {
    key: "employment-history",
    title: "Employment History",
    documentType: ENROLLME_DOCUMENT_TYPES.DRIVER_APPLICATION,
    stage: "Intake",
  },
  {
    key: "agreement",
    title: "Independent Contractor Agreement Review and Signature",
    documentType: ENROLLME_DOCUMENT_TYPES.INDEPENDENT_CONTRACTOR_AGREEMENT,
    stage: "Document Review and Signature",
  },
  {
    key: "quiz",
    title: "Agreement Quiz and Acknowledgment",
    documentType: ENROLLME_DOCUMENT_TYPES.AGREEMENT_QUIZ,
    stage: "Agreement Quiz",
  },
  {
    key: "training-acknowledgment",
    title: "Training and Policy Acknowledgment",
    documentType: ENROLLME_DOCUMENT_TYPES.TRAINING_ACKNOWLEDGMENT,
    stage: "Document Review and Signature",
  },
  {
    key: "optional-documents",
    title: "Admin-Managed Compliance Items",
    documentType: ENROLLME_DOCUMENT_TYPES.WC43_REJECTION,
    stage: "Final Review",
  },
  {
    key: "review-submit",
    title: "Final Review and Submit",
    documentType: null,
    stage: "Final Review",
  },
];

export const DEFAULT_REQUIRED_DOCUMENTS = [
  ENROLLME_DOCUMENT_TYPES.DRIVER_APPLICATION,
  ENROLLME_DOCUMENT_TYPES.INDEPENDENT_CONTRACTOR_AGREEMENT,
  ENROLLME_DOCUMENT_TYPES.AGREEMENT_QUIZ,
  ENROLLME_DOCUMENT_TYPES.TRAINING_ACKNOWLEDGMENT,
  ENROLLME_DOCUMENT_TYPES.VIOLATION_CERTIFICATION,
];

export const DEFAULT_OPTIONAL_DOCUMENTS = [
  ENROLLME_DOCUMENT_TYPES.WC43_REJECTION,
  ENROLLME_DOCUMENT_TYPES.VEHICLE_INSPECTION,
  ENROLLME_DOCUMENT_TYPES.PREVENTIVE_MAINTENANCE,
];

export const DOCUMENT_TEMPLATE_DEFINITIONS = [
  {
    documentType: ENROLLME_DOCUMENT_TYPES.DRIVER_APPLICATION,
    title: "New Driver Employment Application",
    purpose: "Collect driver identity, licensing, accident, violation, employment, and safety-performance history.",
    originalFilePath: "completebeforehiring/New Driver Employment Application.pdf",
    originalFileName: "New Driver Employment Application.pdf",
    requiredDefault: true,
    isFillableOnline: true,
    isGeneratedBySystem: true,
    isAdminTrackedExternally: false,
    isConditional: false,
    isBlankDownloadable: true,
    version: "2026-04",
    notes: "Driver completes and signs online. Admin should review for completeness before approval.",
  },
  {
    documentType: ENROLLME_DOCUMENT_TYPES.WC43_REJECTION,
    title: "WC43 Rejection of Coverage",
    purpose: "Colorado workers' compensation coverage rejection form for eligible ownership/member/partner scenarios.",
    originalFilePath: "completebeforehiring/WC43 - Rejection of Coverage.pdf",
    originalFileName: "WC43 - Rejection of Coverage.pdf",
    requiredDefault: false,
    isFillableOnline: false,
    isGeneratedBySystem: false,
    isAdminTrackedExternally: true,
    isConditional: true,
    isBlankDownloadable: true,
    version: "2026-04",
    notes: "Conditional admin-tracked external record. The app tracks status only and does not upload this file.",
    complianceReminder: "TODO legal/compliance review: confirm WC43 applicability before requiring this document.",
  },
  {
    documentType: ENROLLME_DOCUMENT_TYPES.INDEPENDENT_CONTRACTOR_AGREEMENT,
    title: "Independent Contractor Agreement",
    purpose: "Driver agreement for Trans Voyage Taxi, LLC operations, payments, vehicle duties, conduct, and compliance.",
    originalFilePath: "completebeforehiring/Independent Contractor Agreement.docx",
    originalFileName: "Independent Contractor Agreement.docx",
    requiredDefault: true,
    isFillableOnline: true,
    isGeneratedBySystem: true,
    isAdminTrackedExternally: false,
    isConditional: false,
    isBlankDownloadable: true,
    version: "2026-04",
    notes: "Driver signs online. Company signature fields remain pending for manual company signature if needed.",
  },
  {
    documentType: ENROLLME_DOCUMENT_TYPES.AGREEMENT_QUIZ,
    title: "Agreement Quiz Result and Acknowledgment",
    purpose: "Training and comprehension record tied to the Independent Contractor Agreement.",
    originalFilePath: "completebeforehiring/Independent Contractor Agreement.docx",
    originalFileName: "Independent Contractor Agreement.docx",
    requiredDefault: true,
    isFillableOnline: true,
    isGeneratedBySystem: true,
    isAdminTrackedExternally: false,
    isConditional: false,
    isBlankDownloadable: false,
    version: "2026-04",
    notes: "Generated by system after the agreement quiz. Wrong answers show explanations and remain part of the training record.",
  },
  {
    documentType: ENROLLME_DOCUMENT_TYPES.TRAINING_ACKNOWLEDGMENT,
    title: "Training and Policy Acknowledgment",
    purpose: "Driver acknowledgment of training, policy review, agreement explanation, and opportunity for questions.",
    originalFilePath: "completebeforehiring/Independent Contractor Agreement.docx",
    originalFileName: "Independent Contractor Agreement.docx",
    requiredDefault: true,
    isFillableOnline: true,
    isGeneratedBySystem: true,
    isAdminTrackedExternally: false,
    isConditional: false,
    isBlankDownloadable: false,
    version: "2026-04",
    notes: "Generated and signed online after the quiz is completed and acknowledged.",
  },
  {
    documentType: ENROLLME_DOCUMENT_TYPES.VIOLATION_CERTIFICATION,
    title: "Record of Violation + Annual Review",
    purpose: "Driver certifies 12-month violations; manager completes annual review after MVR review.",
    originalFilePath: "PUC Required/Record of Violation + Annual Review.pdf",
    originalFileName: "Record of Violation + Annual Review.pdf",
    requiredDefault: true,
    isFillableOnline: true,
    isGeneratedBySystem: true,
    isAdminTrackedExternally: false,
    isConditional: false,
    isBlankDownloadable: true,
    version: "2026-04",
    notes: "Driver certification is online. Admin annual review/MVR fields are completed later by management.",
  },
  {
    documentType: ENROLLME_DOCUMENT_TYPES.VEHICLE_INSPECTION,
    title: "Vehicle Inspection Report for 15 passengers or less",
    purpose: "Colorado PUC Rule 6104 vehicle inspection record, including wheelchair-accessible vehicle items when applicable.",
    originalFilePath: "Readytodownload/Vehicle Inspection Report for 15pass or less.pdf",
    originalFileName: "Vehicle Inspection Report for 15pass or less.pdf",
    requiredDefault: false,
    isFillableOnline: false,
    isGeneratedBySystem: false,
    isAdminTrackedExternally: true,
    isConditional: true,
    isBlankDownloadable: true,
    version: "2026-04",
    notes: "Blank download and admin-tracked external record. The app does not upload inspection files.",
  },
  {
    documentType: ENROLLME_DOCUMENT_TYPES.PREVENTIVE_MAINTENANCE,
    title: "Preventive Maintenance Plan",
    purpose: "Vehicle service schedule and maintenance tracking record.",
    originalFilePath: "Readytodownload/Preventative Maintenance Plan #1.pdf",
    originalFileName: "Preventative Maintenance Plan #1.pdf",
    requiredDefault: false,
    isFillableOnline: false,
    isGeneratedBySystem: false,
    isAdminTrackedExternally: true,
    isConditional: true,
    isBlankDownloadable: true,
    version: "2026-04",
    notes: "Blank download and admin-tracked external record. The app does not upload maintenance files.",
  },
];

export const AGREEMENT_VERSION = "trans-voyage-ic-agreement-2026-04";

export const AGREEMENT_QUIZ_QUESTIONS = [
  {
    id: "contractor_status",
    prompt: "Under the agreement, what is the driver's relationship to Trans Voyage Taxi, LLC?",
    options: [
      "The driver is an employee of Trans Voyage Taxi, LLC.",
      "The driver is an independent contractor responsible for their own business obligations.",
      "The driver becomes an employee after the first lease week.",
    ],
    correctAnswer: "The driver is an independent contractor responsible for their own business obligations.",
    explanation: "The agreement states the driver operates as an independent contractor, not as an employee.",
    section: "Independent Contractor Status",
  },
  {
    id: "taxes",
    prompt: "Who is responsible for tax filings and independent business obligations?",
    options: [
      "The driver.",
      "Only the company payroll department.",
      "The passenger if a trip is paid by voucher.",
    ],
    correctAnswer: "The driver.",
    explanation: "Independent contractor status means the driver is responsible for taxes and business obligations.",
    section: "Taxes and Business Obligations",
  },
  {
    id: "credentials",
    prompt: "Which operating credentials must the driver keep current?",
    options: [
      "Only a cell phone.",
      "Licenses, permits, airport credentials, insurance eligibility, and lawful operating status.",
      "Only the vehicle color approval.",
    ],
    correctAnswer: "Licenses, permits, airport credentials, insurance eligibility, and lawful operating status.",
    explanation: "The agreement requires the driver to maintain lawful eligibility and required credentials.",
    section: "Licenses, Permits, Airport Access, and Insurance Eligibility",
  },
  {
    id: "vehicle_condition",
    prompt: "Who is responsible for keeping the vehicle safe, clean, maintained, repaired, and roadworthy?",
    options: [
      "The driver.",
      "The last passenger of each shift.",
      "Only airport staff.",
    ],
    correctAnswer: "The driver.",
    explanation: "The agreement places vehicle condition, maintenance, repairs, cleanliness, and roadworthiness on the driver.",
    section: "Vehicle Responsibility",
  },
  {
    id: "company_restriction",
    prompt: "What may the company do if a vehicle is unsafe or noncompliant?",
    options: [
      "Ignore the issue until the next invoice.",
      "Inspect or restrict the vehicle from company-affiliated operation.",
      "Require passengers to approve repairs.",
    ],
    correctAnswer: "Inspect or restrict the vehicle from company-affiliated operation.",
    explanation: "The agreement allows inspection and restriction of unsafe or noncompliant vehicles.",
    section: "Safety and Compliance Inspection",
  },
  {
    id: "lease_week",
    prompt: "The lease week runs on which schedule?",
    options: ["Monday through Sunday.", "Tuesday through Monday.", "Friday through Thursday."],
    correctAnswer: "Monday through Sunday.",
    explanation: "The agreement sets the lease week as Monday through Sunday.",
    section: "Lease Week and Invoices",
  },
  {
    id: "invoice_day",
    prompt: "When are invoices issued?",
    options: ["Sunday morning.", "Tuesday.", "Only when the driver asks."],
    correctAnswer: "Tuesday.",
    explanation: "Invoices are issued Tuesday under the agreement.",
    section: "Invoice Schedule",
  },
  {
    id: "payment_deadline",
    prompt: "When is payment due unless written authorization says otherwise?",
    options: ["By Sunday.", "By the end of the month.", "No fixed deadline."],
    correctAnswer: "By Sunday.",
    explanation: "Payment is due by Sunday unless there is written authorization saying otherwise.",
    section: "Payment Terms",
  },
  {
    id: "unpaid_consequences",
    prompt: "If unpaid by the Tuesday after the Sunday deadline, what may the company do?",
    options: [
      "Suspend airport access, remove insurance participation, restrict dispatch/system access, or terminate.",
      "Only add a friendly reminder with no operational effect.",
      "Require passengers to pay the invoice.",
    ],
    correctAnswer: "Suspend airport access, remove insurance participation, restrict dispatch/system access, or terminate.",
    explanation: "The agreement gives the company these remedies when payment remains unpaid after the stated deadline.",
    section: "Nonpayment and Suspension",
  },
  {
    id: "report_events",
    prompt: "Which events must be reported immediately?",
    options: [
      "Only accidents with visible damage.",
      "Accidents, incidents, claims, passenger injuries, property damage, police interaction, citations, complaints, regulatory inquiries, and safety events.",
      "Only passenger compliments.",
    ],
    correctAnswer:
      "Accidents, incidents, claims, passenger injuries, property damage, police interaction, citations, complaints, regulatory inquiries, and safety events.",
    explanation: "The agreement requires immediate reporting of these safety, claim, police, citation, complaint, and regulatory events.",
    section: "Accident, Incident, and Claim Reporting",
  },
  {
    id: "no_fault_admission",
    prompt: "After an accident or claim, what must the driver avoid unless authorized in writing?",
    options: [
      "Admitting fault, settling claims, promising payment, or speaking on behalf of the company.",
      "Calling management.",
      "Collecting basic incident details.",
    ],
    correctAnswer: "Admitting fault, settling claims, promising payment, or speaking on behalf of the company.",
    explanation: "The agreement prohibits unauthorized admissions, settlements, payment promises, or company statements.",
    section: "Claims Communication",
  },
  {
    id: "hos",
    prompt: "What must the driver follow regarding hours and fatigue?",
    options: [
      "Hours-of-service, fatigue, safety, and legal requirements.",
      "Only personal preference.",
      "Only the passenger's requested arrival time.",
    ],
    correctAnswer: "Hours-of-service, fatigue, safety, and legal requirements.",
    explanation: "The agreement requires compliance with hours-of-service, fatigue, safety, and legal requirements.",
    section: "Hours of Service and Fatigue",
  },
  {
    id: "impaired_driving",
    prompt: "Which operation is prohibited?",
    options: [
      "Operating impaired, fatigued, distracted, texting unlawfully, or under impairing substances.",
      "Taking a required rest break.",
      "Reporting a safety issue.",
    ],
    correctAnswer: "Operating impaired, fatigued, distracted, texting unlawfully, or under impairing substances.",
    explanation: "The agreement prohibits unsafe operation caused by impairment, fatigue, distraction, unlawful texting, or substances.",
    section: "Safety Rules",
  },
  {
    id: "conduct",
    prompt: "Which conduct is prohibited?",
    options: [
      "Harassment, fraud, voucher manipulation, and unauthorized charges.",
      "Keeping receipts.",
      "Returning lost property.",
    ],
    correctAnswer: "Harassment, fraud, voucher manipulation, and unauthorized charges.",
    explanation: "The code of conduct prohibits harassment, fraud, voucher manipulation, and unauthorized charges.",
    section: "Code of Conduct",
  },
  {
    id: "unauthorized_platform",
    prompt: "Can the driver use company-insured/company-affiliated vehicles or credentials for unauthorized rideshare or competing platform activity?",
    options: [
      "Yes, anytime.",
      "No, not without written authorization.",
      "Only on Tuesdays.",
    ],
    correctAnswer: "No, not without written authorization.",
    explanation: "The agreement requires written authorization for that kind of activity.",
    section: "Unauthorized Platform Activity",
  },
  {
    id: "lost_property",
    prompt: "What must happen with lost property?",
    options: [
      "It must be reported and returned properly.",
      "It can be kept after 24 hours.",
      "It should be ignored unless a passenger calls twice.",
    ],
    correctAnswer: "It must be reported and returned properly.",
    explanation: "Lost property must be handled through proper reporting and return procedures.",
    section: "Lost Property",
  },
  {
    id: "smoking",
    prompt: "What does the agreement say about smoking or vaping in company-affiliated service vehicles?",
    options: [
      "It is allowed if the windows are open.",
      "It is prohibited when it creates odor, cleanliness, safety, or customer concerns.",
      "It is required between trips.",
    ],
    correctAnswer: "It is prohibited when it creates odor, cleanliness, safety, or customer concerns.",
    explanation: "Smoking/vaping is prohibited when it creates odor, cleanliness, safety, or customer concerns.",
    section: "No Smoking / Clean Vehicle Rules",
  },
  {
    id: "policy_updates",
    prompt: "How may company policies, rates, fees, and procedures be updated?",
    options: [
      "By written notice.",
      "Only by rewriting every signed document.",
      "Only by passenger vote.",
    ],
    correctAnswer: "By written notice.",
    explanation: "The agreement allows policy, rate, fee, and procedure updates by written notice.",
    section: "Policy Updates",
  },
  {
    id: "driver_notice",
    prompt: "Which changes or issues must the driver immediately notify the company about?",
    options: [
      "License suspension, address changes, insurance status changes, vehicle status changes, arrests, charges, citations, or eligibility issues.",
      "Only vacation plans.",
      "Only a change in favorite dispatch area.",
    ],
    correctAnswer:
      "License suspension, address changes, insurance status changes, vehicle status changes, arrests, charges, citations, or eligibility issues.",
    explanation: "The agreement requires prompt notice of changes affecting eligibility, licensing, insurance, vehicles, and legal status.",
    section: "Driver Notice Obligations",
  },
];

export const COMPLIANCE_CHECKLIST_ITEMS = [
  { key: "driver_license_copy", label: "Driver license copy", category: "Driver File", requiredDefault: true },
  { key: "mvr", label: "Motor Vehicle Record (MVR)", category: "Driver File", requiredDefault: true },
  { key: "background_check", label: "Background check result", category: "Screening", requiredDefault: true },
  { key: "fingerprint_qualification", label: "Fingerprint qualification status, if applicable", category: "Screening", requiredDefault: false },
  { key: "medical_certificate", label: "Medical certificate, if applicable", category: "Regulatory", requiredDefault: false, appliesWhen: "cdlRequired" },
  { key: "proof_of_insurance", label: "Proof of insurance or company insurance eligibility record", category: "Insurance", requiredDefault: true },
  { key: "vehicle_registration", label: "Vehicle registration", category: "Vehicle", requiredDefault: false, appliesWhen: "requireVehicleInspection" },
  { key: "vehicle_inspection_report", label: "Vehicle inspection report", category: "Vehicle", requiredDefault: false, appliesWhen: "requireVehicleInspection" },
  { key: "preventive_maintenance_plan", label: "Preventive maintenance plan", category: "Vehicle", requiredDefault: false, appliesWhen: "requirePreventiveMaintenance" },
  { key: "wc43_rejection", label: "WC43 rejection of coverage, if applicable", category: "Regulatory", requiredDefault: false, appliesWhen: "includeWc43" },
  { key: "airport_badge", label: "Airport badge/credential, if applicable", category: "Airport", requiredDefault: false },
  { key: "wheelchair_accessible_vehicle", label: "Wheelchair-accessible vehicle checklist, if applicable", category: "Vehicle", requiredDefault: false, appliesWhen: "wheelchairAccessible" },
  { key: "w9", label: "W-9 for independent contractor payment/tax records", category: "Tax", requiredDefault: true },
  { key: "emergency_contact", label: "Emergency contact", category: "Driver File", requiredDefault: true },
  { key: "company_required_record", label: "Other company-required record", category: "Company Policy", requiredDefault: false },
];

export const ADMIN_COMPLIANCE_CHECKLIST_STATUSES = [
  "not_applicable",
  "pending",
  "received_externally",
  "verified",
  "expired",
  "needs_correction",
];
